# 3. Hafta Ödevi: NumPy ile Verinin Matematiği

**Menti:** Burçinnur Alkan  
**Konu:** NumPy Dizileri, Matris İndeksleme, Operasyonlar  
**Haftalık Görev:** Klasik döngülerle NumPy vektörel işlemlerinin **çalışma hızı farkını** test etmek.

Bu ödevde NumPy'nin temellerini gösterdim ve büyük bir veri üzerinde klasik `for` döngüsünün NumPy'ye göre **ne kadar yavaş** olduğunu ölçtüm.

## 1. NumPy Dizileri (Array) Temelleri

In [4]:
import numpy as np

# Listeden dizi olusturma
dizi = np.array([10, 20, 30, 40, 50])
print("Dizi:", dizi)
print("Tipi:", type(dizi))
print("Boyutu (shape):", dizi.shape)
print("Veri tipi (dtype):", dizi.dtype)

# Hazir dizi uretme yollari
print("\nSifirlar:", np.zeros(5))
print("Birler:", np.ones(3))
print("Aralik (0-10, 2 adim):", np.arange(0, 10, 2))
print("Esit araliklı 5 sayi (0-1):", np.linspace(0, 1, 5))

Dizi: [10 20 30 40 50]
Tipi: <class 'numpy.ndarray'>
Boyutu (shape): (5,)
Veri tipi (dtype): int64

Sifirlar: [0. 0. 0. 0. 0.]
Birler: [1. 1. 1.]
Aralik (0-10, 2 adim): [0 2 4 6 8]
Esit araliklı 5 sayi (0-1): [0.   0.25 0.5  0.75 1.  ]


## 2. Vektörel İşlemler

NumPy'nin gücü: bir işlemi tek satırda **tüm dizi** üzerinde uygulayabilmesi (döngüye gerek yok).

In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a + b =", a + b)
print("a * 2 =", a * 2)
print("a ** 2 =", a ** 2)
print("a * b =", a * b)

# Hazir istatistik fonksiyonlari
print("\nToplam:", a.sum())
print("Ortalama:", a.mean())
print("En buyuk:", a.max())
print("Standart sapma:", a.std())

a + b = [11 22 33 44]
a * 2 = [2 4 6 8]
a ** 2 = [ 1  4  9 16]
a * b = [ 10  40  90 160]

Toplam: 10
Ortalama: 2.5
En buyuk: 4
Standart sapma: 1.118033988749895


## 3. Matris (2 Boyutlu Dizi) ve İndeksleme

In [6]:
matris = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matris:\n", matris)
print("\nBoyut:", matris.shape)

# Indeksleme: [satir, sutun]
print("\n1. satir 2. sutun (6):", matris[1, 2])
print("Ilk satir:", matris[0])
print("Ilk sutun:", matris[:, 0])
print("Kose parcasi (ilk 2x2):\n", matris[:2, :2])

# Kosullu (boolean) indeksleme
print("\n5'ten buyuk elemanlar:", matris[matris > 5])

Matris:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Boyut: (3, 3)

1. satir 2. sutun (6): 6
Ilk satir: [1 2 3]
Ilk sutun: [1 4 7]
Kose parcasi (ilk 2x2):
 [[1 2]
 [4 5]]

5'ten buyuk elemanlar: [6 7 8 9]


## 4. ⭐ ASIL GÖREV: Hız Karşılaştırması (Döngü vs NumPy)

10 milyon elemanlı bir dizinin karelerinin toplamını iki yöntemle hesaplayıp süreleri karşılaştıracağım.

In [ ]:
import time

N = 10_000_000
# dtype=float64: karelerin toplami cok buyuk (3.3 x 10^20) oldugu icin int64'e sigmaz -> overflow.
# float64 cok daha buyuk degerleri tutabildigi icin tasma uyarisi olusmaz.
veri = np.arange(N, dtype=np.float64)

# --- Yontem 1: Klasik Python for dongusu ---
baslangic = time.time()
toplam_dongu = 0
for x in veri:
    toplam_dongu += x * x
sure_dongu = time.time() - baslangic
print(f"Dongu ile sonuc : {toplam_dongu}")
print(f"Dongu suresi    : {sure_dongu:.4f} saniye")

In [9]:
# --- Yontem 2: NumPy vektorel islem ---
baslangic = time.time()
toplam_numpy = np.sum(veri ** 2)
sure_numpy = time.time() - baslangic
print(f"NumPy ile sonuc : {toplam_numpy}")
print(f"NumPy suresi    : {sure_numpy:.4f} saniye")

NumPy ile sonuc : 1291890006563070912
NumPy suresi    : 0.0305 saniye


In [10]:
# --- Karsilastirma ---
hizlanma = sure_dongu / sure_numpy
print("=" * 40)
print(f"Dongu suresi : {sure_dongu:.4f} sn")
print(f"NumPy suresi : {sure_numpy:.4f} sn")
print(f"NumPy yaklasik {hizlanma:.0f} KAT daha hizli!")
print("=" * 40)

Dongu suresi : 0.8870 sn
NumPy suresi : 0.0305 sn
NumPy yaklasik 29 KAT daha hizli!


## 5. Sonuç ve Yorum

- NumPy dizileri, aynı tipteki verileri bellekte **art arda** tutar ve işlemleri C dilinde derlenmiş kodla yapar. Bu yüzden Python'un tek tek eleman gezen `for` döngüsünden **çok daha hızlıdır**.
- Veri büyüdükçe aradaki fark **katlanarak** açılır. Bu yüzden veri biliminde büyük veriyle çalışırken döngü yerine mümkün olduğunca **vektörel işlemler** tercih edilir.
- **Öğrendiğim en önemli şey:** "Doğru sonuç" yeterli değil; büyük veride *hızlı* sonuç da önemli. NumPy tam olarak bunu sağlıyor.